apiVersion: v1
kind: Pod
metadata:
  name: jenkins-slave
spec:
  containers:
  - name: jenkins-slave
    image: satishrawat/jenkins:lts
    workingDir: /var/jenkins_home
    imagePullPolicy: IfNotPresent
    tty: true
  
    volumeMounts:
      - name: docker
        mountPath: /var/run/docker.sock
  volumes:
  - name: docker
    hostPath:
      path: /var/run/docker.sock
