apiVersion: v1
kind: Service
metadata:
  name: test-service
  labels:
    app: test
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8010
  selector:
    app: test
  type: LoadBalancer


---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: test
spec:
  replicas: 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
        - image: gcr.io/jenkins-cd-228702/test-app:13
          imagePullPolicy: Always
          name: test
          ports:
            - containerPort: 8010
